version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=local123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=neodrive
    restart: unless-stopped
    networks:
      - neodrive-net
  # APP*****************************************
  neodrive:
    image: cooptalent/neodrive-backend
    container_name: neodrive-backend
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - neodrive-net
volumes:
  postgres-data: {}

networks:
  neodrive-net:
    driver: bridge