version: "3.4"

services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4:4.24
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@urnacare.com
      PGADMIN_DEFAULT_PASSWORD: local123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  postgres:
    restart: always
    image: postgres:12
    container_name: "postgres-local"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: local123
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
  pgadmin_data: