spring:
  application:
    name: urnacare
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
  mvc:
    favicon:
      enabled: false
    thymeleaf:
      mode: HTML
logging:
  level:
    root: DEBUG
    com.urna.urnacare: DEBUG
application:
    mail:
      from: urnacare@localhost
    async:
      core-pool-size: 2
      max-pool-size: 50
      queue-capacity: 10000
    swagger:
        default-include-pattern: /api/.*
        title: Urnacare API
        description: Urnacare API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name: Kalyan Das
        contact-url: www.urnacare.com
        contact-email: technakriti@gmail.com
        license:
        license-url: