CREATE TABLE state (
    code VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	PRIMARY KEY (code)
);

CREATE TABLE currency (
	code VARCHAR(50) NOT NULL,
	symbol VARCHAR(50),
	name VARCHAR(50) NOT NULL,
	PRIMARY KEY (code)
);

CREATE TABLE country (
    code VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	PRIMARY KEY (code)
);